//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTcms.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_article_tags_relation
    {
        public int id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> article_id { get; set; }
        public Nullable<int> tag_id { get; set; }
    }
}
