//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTcms.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_site_channel_field
    {
        public int id { get; set; }
        public Nullable<int> channel_id { get; set; }
        public Nullable<int> field_id { get; set; }
    
        public virtual dt_article_attribute_field dt_article_attribute_field { get; set; }
        public virtual dt_site_channel dt_site_channel { get; set; }
    }
}
