//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTcms.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_user_addr_book
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string user_name { get; set; }
        public string accept_name { get; set; }
        public string area { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string telphone { get; set; }
        public string email { get; set; }
        public string post_code { get; set; }
        public Nullable<byte> is_default { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    }
}
